export const INCREASE_COUNTER_1 = 'INCREASE_COUNTER_1'
export const DECREASE_COUNTER_1 = 'DECREASE_COUNTER_1'
export const INCREASE_COUNTER_2 = 'INCREASE_COUNTER_2'
export const DECREASE_COUNTER_2 = 'DECREASE_COUNTER_2'